language: elixir
elixir: 1.9.1
otp_release: 22.0

cache:
  directories:
    - _build
    - deps

before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - MIX_ENV=test mix do clean, compile --warnings-as-errors
  - travis_wait mix dialyzer --plt

script:
  - mix test
  - mix format --check-formatted
  - mix credo --strict
  - mix dialyzer --format short
  # Check for unused dependencies
  - mix deps.unlock --unused && git diff --exit-code
