language: elixir
elixir: 1.9.1
otp_release: 22.0

cache:
  directories:
    - _build
    - deps

services:
  - docker

addons:
  chrome: stable

before_install:
  # ChromeDriver
  - export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo chmod +x chromedriver
  - sudo mv chromedriver /usr/local/bin
  - nohup chromedriver &
  - sleep 10 &
  - cat nohup.out
  # PhantomJS
  - phantomjs --wd 2>&1 > phantomjs.log &
  # Allow accessing localhost ports from docker containers.
  # See https://github.com/qoomon/docker-host
  - docker run --name 'dockerhost' --cap-add=NET_ADMIN --cap-add=NET_RAW --restart on-failure -d qoomon/docker-host
  # Selenium - ChromeDriver
  - docker run -d -p 4444:4444 --shm-size=2g --link 'dockerhost' selenium/standalone-chrome:3.141.59-vanadium
  - docker run -d -p 4447:4444 --shm-size=2g --link 'dockerhost' selenium/standalone-chrome:2.53.1
  # Selenium - Firefox
  - docker run -d -p 4445:4444 --shm-size=2g --link 'dockerhost' selenium/standalone-firefox:3.141.59-vanadium
  - docker run -d -p 4446:4444 --shm-size=2g --link 'dockerhost' selenium/standalone-firefox:2.53.1


before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - MIX_ENV=test mix do clean, compile --warnings-as-errors
  - travis_wait mix dialyzer --plt

script:
  - mix test
  - mix format --check-formatted
  - mix credo --strict
  - mix dialyzer --format short
  # Check for unused dependencies
  - mix deps.unlock --unused && git diff --exit-code
  - mix test --only integration_test_driver:chromedriver
  - mix test --only integration_test_driver:phantomjs
  # Selenium 3, firefox
  # TEST_SERVER_HOSTNAME idea came from here: https://stackoverflow.com/a/43541732/614775
  - TEST_SERVER_HOSTNAME="dockerhost" SELENIUM_BASE_URL="http://localhost:4445/wd/hub" mix test --only integration_test_driver_browser:selenium-firefox
  # Selenium 2, firefox
  - TEST_SERVER_HOSTNAME="dockerhost" SELENIUM_BASE_URL="http://localhost:4446/wd/hub" mix test --only integration_test_driver_browser:selenium-firefox
  # Selenium 3, chrome
  - TEST_SERVER_HOSTNAME="dockerhost" mix test --only integration_test_driver_browser:selenium-chrome
  # Selenium 2, chrome
  - TEST_SERVER_HOSTNAME="dockerhost" SELENIUM_BASE_URL="http://localhost:4447/wd/hub" mix test --only integration_test_driver_browser:selenium-chrome
